### ISSUE TITLE
Adding label to TimeProperty-Date

### ISSUE THREAD

**Issue by timathom** [sparna-git/Sparnatural#263]
I am defining a `birthDate` property and would like to include the person label as shown in the dbpedia-v2 demo:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
SELECT DISTINCT ?this ?this_label WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>.
  ?this <http://dbpedia.org/ontology/birthDate> ?Date_1.
  FILTER(((xsd:dateTime(?Date_1)) >= "1928-01-01T00:00:00"^^xsd:dateTime) && ((xsd:dateTime(?Date_1)) <= "1948-01-01T00:00:00"^^xsd:dateTime))
  ?this <http://www.w3.org/2000/01/rdf-schema#label> ?this_label.
  FILTER(LANGMATCHES(LANG(?this_label), "en"))
}
LIMIT 1000
```

However, when I use the same property definition as the one in the demo, the generated SPARQL doesn't include the label pattern:

``` 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://www.cidoc-crm.org/cidoc-crm/E21_Person>.
  ?this (<http://www.cidoc-crm.org/cidoc-crm/P98i_was_born>/<http://www.cidoc-crm.org/cidoc-crm/P4_has_time-span>/<http://www.cidoc-crm.org/cidoc-crm/P82a_begin_of_the_begin>) ?Date_1.
  FILTER(((xsd:dateTime(?Date_1)) >= "1928-01-01T00:00:00"^^xsd:dateTime) && ((xsd:dateTime(?Date_1)) <= "1948-01-01T00:00:00"^^xsd:dateTime))
}
LIMIT 1000
```

And I can't see anywhere in the code where this pattern is being injected. Thanks in advance!

**Comment by timathom** [comment]
Thanks again--I see how it works now :) 

What would you suggest for handling a more complex label pattern? For example, something like:

```
?this crm:P1_is_identified_by ?name .
?name crm:P190_has_symbolic_content ?label ; 
           crm:P72_has_language :english ; 
           crm:P2_has_type :primaryName .
```

**Comment by tfrancart** [comment]
Hello @timathom 

This will not work with the "defaultLabel" config property. 

The defaultLabelProperty can point to a property that is itself mapped to a property path (e.g. crm:P1_is_identified_by/crm:P190_has_symbolic_content) but you would miss the criteria on crm:P2_has_type.

If you are reifying the names as entities in the graph, with a type to indicate primary name, then you need to reflect that in the Sparnatural config. This means your users will have to explicitely add one criteria in their query, to traverse the P1 property to the name, then add a second criteria to indicate they want a primary name, and then click on the eye to indicate they want the name to be selected. You can add the "defaultLabelProperty" on your "Name" class to point to P190 so that the literal form of the name is selected, along with the URI of the name entity.

Other possibility is that you insert that as post-processings on the SPARQL query string that Sparnatural outputs, directly as Javascript, using regexes. But this could be tricky.

If you have more information on your porject, with modeling diagrams, use-cases and demo, please share !

**Comment by timathom** [comment]
Thanks, @tfrancart, that all makes sense. I've been testing Sparnatural as a potential query interface for a new search platform my institution, Yale University, is building. I love that Sparnatural is almost completely declarative in its approach.

We're using the Linked Art profile of CIDOC-CRM and building in MarkLogic. More info is available here: https://lux.collections.yale.edu/. I see you've developed a custom search datasource for GraphDB. Would be great to have a generic extensibility mechanism for other platforms as well :)

**Comment by tfrancart** [comment]
Hi @timathom The project is very cool. In particular Sparnatural will fit very well with the "usability" part of the presentation, and the concept of Linked Open **Usable** Data is very relevant for what I do. I will certainly borrow the concept.
FYI the first project in which Sparnatural was developed was based on CIDOC-CRM (http://openarchaeo.huma-num.fr/explorateur/home?lang=en)
Don't hesitate to reach me for support, this is a great use-case for Sparnatural and would get it a wide audience.

Also, FYI some researchers here in France are working on automated Sparnatural configuration from the analysis of the underlying graph data structure. Let me know if you want to learn more.

As for the extensibility for Marklogic : can you provide me with a SPARQL query example of how a custom Marklogic SPARQL query looks like ? I'll see what I can do, but can't promise anything.

Sidenote : I also used shared spreadsheets to edit Sparnatural configurations, such as https://docs.google.com/spreadsheets/d/1S5K7cl-8-JFyqnCZP2pVhI3-E4IK0XgCPElkr657jJg/edit#gid=468548378, used in the demo at http://sparnatural.eu/demos/demo-elzeard/index.html. The spreadsheet is converted to OWL using this online converter https://skos-play.sparna.fr/play/convert (the API of which is not yet publicly advertised, but it is at http://xls2rdf.sparna.fr/rest/convert?url=[URL_of_Excel_export_of_Google_spreadsheet]&noPostProcessings=true )

**Comment by timathom** [comment]
Thanks for the pointers! Yes, I'd be keen to learn more about the automated Sparnatural configuration you mention. Regarding MarkLogic, I don't have a good example yet, but I think in general it might be helpful to be able to define a custom `queryString` for `SearchProperty` in the same way as `AutocompleteProperty`.

**Comment by tfrancart** [comment]
Note that an integration with a proprietary SPARQL search feature requires an integration at two places:

1. to fuel the autocomplete properties with a custom SPARQL query (and that is already possible)
2. to generate the final SPARQL query with a proprietary, custom, piece of SPARQL. And that is different and trickier, since we are talking here about only a piece of SPARQL inserted in the final query, for which we don't know in advance the subject variable name, the required prefixes (if any), etc. This is why this custom generation of that piece of the SPARQL query is currently done via code, and note through a configuration.

**Comment by timathom** [comment]
Thanks again, going to close this now.
