### ISSUE TITLE
double class GroupContenaire in code

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#289]
Hi,
If I may ask a further question: I noticed some things I'm not able to understand properly in sparnatural.js
for example:
1.
https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/sparnatural.js#L1012-L1017

VS:
https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/SparnaturalComponents.js#L72-L81

Why the double class? The one in the SparnaturalComponents seems nicely object oriented while the other in sparnatural.js Seems a bit out of place. and from the first look, it looks like they are doing the same thing.

2. And what is the purpose of these two lines?
https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/sparnatural.js#L1047-L1048
especially the base() method doesn't seem to do anything? or am I mistaken?

best regards!

**Comment by tfrancart** [comment]
Please ask questions.

This is due to code refactoring.

The various components of the UI have been migrated from sparnatural.js to SparnaturalComponents, in a more object-oriented style. However some components have not been migrated, because it is complicated : EndClassWidgetGroup, ActionsGroup, ActionWhere, ActionAnd, ActionRemove, ObjectPropertyTypeWidget. Those are still referring to the "GroupContenaire" you see in sparnatural.js, while the ones in SparnaturalComponents are referring to the one in SparnaturalComponents.

There are dependencies to global functions (if I remember correctly) that make the migration of these components a bit complicated.

**Comment by SteinerPascal** [comment]
okay that's what i assumed. I'm currently looking at it so i can refactor those components too. But i guess since it's js I'm refactoring i will break quite a few things. Anyway I will give it a try this week.
For the global functions. Do you remember wether it were these two functions or different ones outside sparnatural.js?
1. https://github.com/sparna-git/Sparnatural/blob/c1f49a9f7074001d544ede6830d78bf62a891eba/src/sparnatural.js#L764
2. https://github.com/sparna-git/Sparnatural/blob/c1f49a9f7074001d544ede6830d78bf62a891eba/src/sparnatural.js#L809

**Comment by SteinerPascal** [comment]
Just did a quick check. I can see that the class:
https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/SparnaturalComponents.js#L5
Corresponds to the class:
https://github.com/sparna-git/Sparnatural/blob/c1f49a9f7074001d544ede6830d78bf62a891eba/src/sparnatural.js#L2053
Let me see if there is a good construct in ts where i can structure the legacy classes.

**Comment by tfrancart** [comment]
> For the global functions. Do you remember wether it were these two functions or different ones outside sparnatural.js?

Yes, especially the `addComponent` one

And, yes HTMLComponent inherited from what was defined in GenericTools
