### ISSUE TITLE
How to return the values of dates?

### ISSUE THREAD

**Issue by lubianat** [sparna-git/Sparnatural#326]
Hello, 

I am trying to return the values of dates in a query, here is the example: 

![image](https://user-images.githubusercontent.com/7917951/174316434-ef513d7f-44ff-43f5-a5c9-a3899282f380.png)

I thought about using [core:defaultLabelProperty](http://data.sparna.fr/ontologies/sparnatural-config-core#defaultLabelProperty) to configure it, but the date will not have a label right? 

Do you have a suggestion on how I could trick Sparnatural into providing not `?Date_1_label` but `?_Date1` ? 

Thanks!

**Comment by tfrancart** [comment]
You are overcomplicating things. You don't need defaultLabelProperty for literal values, only for URI. Simply remove it from your configuration on Dates.

Look at [this query](http://sparnatural.eu/demos/demo-dbpedia-v2/?query=XQAAAAKzAQAAAAAAAABtAFGGLy3h63L38oyT7TBxA1mn6LbPSJ2NMVO4Vg4lKkLS4FqMEZ_eH4Ag5ZiaNgt7wKsXHbhzPyra3OsRPEz0rFgnSme_BWFDvYHSqTR5rEBHG0c_ZJyzVwK5DLg0RgLjJnp4-WiVQkTSVlOWDy9sbvwPcslLzBAQbNbi3_tBW703Uud4fVzvfIeUq1Jc-KscaP8j8p3CA6XiFV_ngGdyrO7DrgVqNIuHhe_-VlX_TKksUd1xy_aJ34L6GaPMRJvor-RWa6o_2uVoxmZIbmMcp4JOApTmcZZCg5x6Xb3oEgMyPQjhCFuykqu380OJV4j_8-qYag) - OK it does not work due to DBPedia/Virtuoso behavior, but the SPARQL is correct).
See equivalent config at https://github.com/sparna-git/sparnatural.eu/blob/main/demos/demo-dbpedia-v2/sparnatural-config.ttl#L291

**Comment by lubianat** [comment]
@tfrancart indeed, you are correct. I had added custom post-processing that was messing up with the SPARQL. All fine now, thanks!
