### ISSUE TITLE
Please pass configured settings for request headers to all AJAX requests.  

### ISSUE THREAD

**Issue by elasticjava** [sparna-git/Sparnatural#448]
Working with secured SPARQL Endpoints I cannot pass authentication and request headers to all used requests.

In particular, the autocompletewidget uses its own AJAX requests, which do not inherit the configured properties of the Yasqe configuration.

It would be great if the Yasqe configuration could also be done via Typescript.

From a certain size of the created combined SPARQL query GET request are unsuitable.
So it would be great if that could be configurable as well.

**Comment by tfrancart** [comment]
Yes I agree. This was registered as an issue in #187 .
I don't have yet a clear idea on what would be the best architecture for this.

**Comment by SteinerPascal** [comment]
@tfrancart should i add an option to adapt the datasource property? From
`"datasource": "datasources:list_rdfslabel_alpha_with_count",`
To:
```
"datasources": {
    "method":"POST",
    "query":"list_rdfslabel_alpha_with_count",
    "auth":{
    "scheme":"basic",
    "parameters": [
        "credentials": "YWxhZGRpbjpvcGVuc2VzYW1l"
      ]
    }
```
or for digest auth:
```
"datasources": {
    "method":"POST",
    "query":"list_rdfslabel_alpha_with_count",
    "auth":{
    "scheme":"digest",
    "parameters": [
        "realm": "<realm>",
        " uri":"<url>",
        "algorithm":"<algorithm>",
        "etc": "..."
      ]
    }
```

**Comment by tfrancart** [comment]
Salut @SteinerPascal 

> @tfrancart should i add an option to adapt the datasource property?

I don't think this should belong to the configuration. The configuration is meant to be "purely" semantic, with the definitions and mappings to classes and properties - and to queries to populate the lists. But the gory auth details of how to authenticate to SPARQL endpoints belong to another level. Typically you can have an ontologist designing the config, and a programmer or devops configuring the auth details.

Besides, this can be easily written in JSON but doing it in OWL (or future SHACL) config would require creating corresponding properties in the config-core or config-datasources ontologies.

What I suggest is to instead pass it as a pure JSON object to Sparnatural, as a map of endpoint/options, something like:

```json
{
  "http://non-default-endpoint.com" : {
    "method":"POST",
    "auth":{
      "scheme":"digest",
      "parameters": [
        "realm": "<realm>",
        " uri":"<url>",
        "algorithm":"<algorithm>",
        "etc": "..."
      ]
  },
 "http://another-endpoint.com" : {
    // other configs for another endpoint
  }
}
```

I don't know if it is possible, but we could use exactly the same structure as for YasQE, so that the same config object can be used for both (?)

Then, when issuing queries, we can use the options provided to issue the request, like at https://github.com/sparna-git/Sparnatural/blob/ba13bd91181cb1dd97c3bac76330dae35413f82a/src/sparnatural/components/widgets/listwidget/ListWidget.ts#L80

So - pretty much what you propose, but not in the config and passed as pure technical parameters to the Sparnatural element.

**Comment by tfrancart** [comment]
Done in #517

**Comment by tfrancart** [comment]
This is now done. The only place where headers are not passed is the initial call to load the configuration file (see #529 )
