### ISSUE TITLE
Find Sub class of a Class

### ISSUE THREAD

**Issue by manikyab** [sparna-git/Sparnatural#531]
Hi @tfrancart,
I am new to sparnatural and I wanted to find out the list of objects in subclass of Class and no of objects having that same type
For Example:
a:Building rdfs:subClassOf a:Location

urn:123-456 rdf:type a:Building

Expected Output->
Building(1)

**Comment by tfrancart** [comment]
Hello

Welcomen first make sure you read http://docs.sparnatural.eu/hello-sparnatural/Hello-Sparnatural.html and http://docs.sparnatural.eu/how-to-configure/How-to-configure-Sparnatural.html

2 ways to do what you want:

1. Add "Building" in your config, so that you will have both Location and Building to select from
2. See https://github.com/sparna-git/Sparnatural/issues/494 . You can use a TreeProperty with the datasources [datasources:tree_children_subClassOf](http://data.sparna.fr/ontologies/sparnatural-config-datasources/tree_children_subClassOf) and [datasources:tree_root_domain_subClassOf](http://data.sparna.fr/ontologies/sparnatural-config-datasources/tree_root_domain_subClassOf)

Also, we are thinking about improving the class selection to make it with 2-levels hierarchy : #351 (in 2024 probably)

**Comment by tfrancart** [comment]
Closing this, feel free to reopen if you have further questions
